### PR TITLE
New schema to replace f142

### PR DESCRIPTION
**Pull request by SkyToGround**
### Description of Work

Replaces _f142_. Removes alarm fields as those have their own schema and replaces the unsigned timestamp with a signed one.

### Issue

* ECDC-2749

### Developer Checklist

- [x] If there are new schema in this PR I have added them to the list in README.md
- [x] If there are breaking changes to a schema, I have used a new file identifier and updated the list in README.md
- [x] There is some documentation here or in the flat buffer file on the use case for this data, including which component is intended to send the data and/or which is the intended receiver.

## Approval Criteria

This PR should not be merged until Tobias R, Mark K and Jack H have given their explicit approval in the comments section.

### CODE REVIEW

**Comment by zjttoefs** [comment]
The table is called "ScalarData" but an array is allowed. I think that makes the naming confusing.

**Comment by SkyToGround** [comment]
@zjttoefs Fair enough moment about the name. With that said, that name was picked based on the fact that this schema will be used (like f142) to forward two different EPICS4 normative types. Namely [NTScalar and NTScalarArray](http://epics-pvdata.sourceforge.net/alpha/normativeTypes/normativeTypes.html#ntscalar). From reading the definition for the word "scalar" in the Oxford English Dictionary, I _think_ `ScalarData` is an appropriate name.

**Comment by mkoennecke** [comment]
I am OK with changing the time stamp to long. But I think the EPICS alarm status should stay in the message. Otherwise code using this has to listen to two types of messages, this one and the alarm message, and correlate them in order to figure out if valid data was received.

**Comment by SkyToGround** [comment]
@mkoennecke I have a few follow up questions to your comment:
1. What code that is in use today needs to correlate values and alarms from a PV? I am aware of no such code.
2. Is it possible to correlate two different flatbuffer messages? (Yes it is.)
3. Do you then suggest that it is better to add these alarms (along with the corresponding serialisation and deserialisation code in our relevant applications) to the `senv` and `tdct` schemas as well as any future EPICS-schema?

**Pull request merged**
