### PR TITLE
EPICS PV alarm state schema

### PR DESCRIPTION
**Pull request by SkyToGround**
### Description of Work

A schema used specifically for EPICS PV alarms. Note that although CA alarms can be mapped to pvAccess alarms, some information is lost in the process. Also, pvAccess alarms can not be mapped to CA alarms. Thus: should CA alarms be a separate field?

### Issue

* ECDC-2749
* ECDC-2792

### Developer Checklist

- [x] If there are new schema in this PR I have added them to the list in README.md
- [x] If there are breaking changes to a schema, I have used a new file identifier and updated the list in README.md
- [x] There is some documentation here or in the flat buffer file on the use case for this data, including which component is intended to send the data and/or which is the intended receiver.

## Approval Criteria

This PR should not be merged until Tobias R, Mark K and Jack H have given their explicit approval in the comments section.

### CODE REVIEW

**Review by zjttoefs — CHANGES_REQUESTED** [review]
This reads like it is two things rolled into one. For ca alarms we get a comprehensive list of options and pv access alarms are apparently a lot less clear.
I think this would be easier to use, if there was either a really combined schema or two separate ones.

**Comment by SkyToGround** [comment]
@zjttoefs I find a bit hard to map your comment onto the technical limitations that we have (i.e. what we get from pvAccess vs channel access). But my impression is that you are (would be) leaning towards discarding the ca-alarms completely. If not, then we will have to discuss the matter to figure out what you want vs what is reasonably possible.

**Comment by zjttoefs** [comment]
At some point we need to decide what to do with the alarm information. The main target is the file writer, for all I know. The reader of the file ideally should not have to care, if the data was made available on ca or pvaccess. Then it would make sense to merge as soon as possible that the source. Failing that we should split this into two different schemas.

**Comment by SkyToGround** [comment]
@zjttoefs Yes, hence my interpretation of discarding CA-alarms seeing as pva-alarms is the lowest common delimiter.

**Comment by mkoennecke** [comment]
I am not in favour of dropping CA alarms. As we do not have the resources to rewrite the world of EPICS, CA is there to stay for a long while.

**Comment by mattclarke** [comment]
Note: needs a closer look as we may want to use this for NICOS as well. NICOS currently uses f142 too

**Comment by zjttoefs** [comment]
Still looks odd to me that the ca version of the alarm states looks a lot richer than that for PVaccess.
My preference would be to not expose the consumer of the schema to the wire protocol used at the lower level, i.e. to not have separate fields for channel access and pvaccess. I'd like to have the states mapped into something that can be generically understood, if possible.

**Comment by mattclarke** [comment]
Me too.
I was wondering if we could do something like a simple severity enum and a catch-all string description: 
enum(ok, minor, major, invalid)
description('lolo or whatever')

**Comment by zjttoefs** [comment]
This would sacrifice the machine readability for the states. That might not be an issue for the file writer. For the consumer of the file it mainly matters if they can trust the readback values or not. If there is doubt the user should (be prompted to) investigate. That's the main thing that needs to be conveyed in a machine readable way. 

How would that look on the NICOS side? I guess there you may additionally care the ability to control the device. But even there presenting the state to the operator is probably the main use case.

I am still curious to find out how the pvaccess alarms came to be the way they look.

**Comment by mattclarke** [comment]
For PVA, alarms are defined as:

```
alarm_t alarm
    int severity
    int status
    string message
```
- severity is no_alarm, minor, etc.

- status is the weird set of enums listed in the file above (device, driver, record, etc.) which classify where in the epics system the alarm comes from. Probably not useful to most applications.

- message has the details, e.g. lolo.

In NICOS, we already convert from epics severity to the status levels NICOS uses. And we grab the message for the details.

**Comment by mattclarke** [comment]
NH says they don't generally bother with the status

**Comment by mattclarke** [comment]
> I am still curious to find out how the pvaccess alarms came to be the way they look.

Design by commitee

**Comment by zjttoefs** [comment]
How about we put the same (or slightly adapted) logic that NICOS has in the forwarder and use a common FB schema for the alarms. The process reading the file should not need to implement parsing pvaccess alarms AND CA alarms. That would essentially mean having only severity and a message.

**Comment by mattclarke** [comment]
That is pretty much what I was thinking 👍

**Comment by mkoennecke** [comment]
I agree with Matt but would like to add an integer field as well which would make automatic processing of errors easier.

**Pull request closed without merging**
