### PR TITLE
Replace log data schema

### PR DESCRIPTION
**Pull request by matthew-d-jones**
### Description of Work

Created a replacement for the f142 schema by removing the obsolete internal forwarder information field and adding the EPICS alarm status for DM-872. Breaking change so requires new schema id.

The default of `NO_CHANGE` for the alarm status indicates that the file writer should not record the alarm status. The producer (forwarder) does not need to populate the field in this case and it uses no space on the wire.

### Developer Checklist

- [x] If there are new schema in this PR I have added them to the list in README.md
- [x] If there are breaking changes to a schema, I have used a new file identifier and updated the list in README.md
- [x] There is some documentation here or in the flat buffer file on the use case for this data, including which component is intended to send the data and/or which is the intended receiver.

*A file identifier can be generated [here](https://www.random.org/strings/?num=1&len=4&digits=on&upperalpha=on&loweralpha=on&unique=on&format=html&rnd=new)*

## Approval Criteria

This PR should not be merged until Tobias R, Mark K and Matthew J have given their explicit approval in the comments section.

### CODE REVIEW

**Comment by zjttoefs** [comment]
Why does this pull request add f144?

**Comment by matthew-d-jones** [comment]
Removing a field is a breaking change to the schema, so requires a new identifier.

**Comment by zjttoefs** [comment]
Then I don't understand why you removed the field on ep00.

The README should spell out what schema to use in the future, if we replace one. No?

**Comment by zjttoefs** [comment]
Should have a discussion on the breaking change, deprecation and deletion processes.

**Comment by zjttoefs** [comment]
@matthew-d-jones maybe bring this up Thursday? deprecation etc.
Or start writing a proposal for a procedure how we handle these cases and we review that in Github.

**Comment by matthew-d-jones** [comment]
6 months later I have no idea what the `ep00` change was here for, so I've reverted that change. I've marked obsolete schema in the readme list with `[OBSOLETE]`.

**Comment by matthew-d-jones** [comment]
I've got back up to speed with the EPICS alarm status work and found that we can update this schema in a non-breaking way. See #46.

**Pull request closed without merging**
