### PR TITLE
f143: Added Pythonic data structures

### PR DESCRIPTION
**Pull request by nikhilbiyani**
- [x] If there are new schema in this PR I have added them to the list in README.md

Added support for following data structures:
- Dictionaries with arbitrary key type and value type
- Arrays can now be of Type List, Tuple or Set

### CODE REVIEW

**Comment by nikhilbiyani** [comment]
We are trying to use f142/f143 to write NICOS cache messages to Kafka. These cache messages contain device parameters and values which can be either numeric/string or can also be dict, tuples, sets, lists, etc. 

- Dict in Python can have Keys of anytype mapped to Values of anytype. This is why new tables were implemented to account for that.

- For arrays, when reading them back into NICOS, I want to see if an array is a list, a tuple or a set. This is now done using a ArrayType union.

**Comment by zjttoefs** [comment]
The initial idea of this schema was to use it for EPICS data. For serialising NICOS device parameters a custom schema may make sense. Have you considered that?
We expect all consumers to be able to understand all of the schema. Adding things that most do not need isn't ideal.

**Comment by matthew-d-jones** [comment]
I thought that f142 was being used so that messages could be pushed directly into the cache, if you are reserialising anyway then I agree with Tobias that we'd be better off with a separate schema.

**Comment by zjttoefs** [comment]
To what extend is this still required if ns11 (#25) goes in?

**Comment by nikhilbiyani** [comment]
This pull request can be dropped if #25 is merged.

**Comment by zjttoefs** [comment]
For the moment let's assume we prefer #25 because it is the later request. We can reopen if that comes out of the discussion.

**Pull request closed without merging**
